services:
  caddy:
    image: caddy:2-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./app:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs:ro
      
    depends_on:
      - php
  
  php:
    build: ./app
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mysql
      - redis
    environment:
      - REDIS_HOST=redis
      - MYSQL_HOST=mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - mysql_data:/var/lib/mysql
      - ./app/sql/db.sql:/docker-entrypoint-initdb.d/db.sql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf:ro

  redis:
    image: redis:7-alpine

volumes:
  mysql_data:
