apiVersion: v1
data:
  Caddyfile: |
    {
      auto_https off
    }
    :80 {
        root * /var/www/html
        php_fastcgi php:9000
        file_server
    }
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: caddy
  name: caddy-caddyfile
