apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml -o kompose
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml -o kompose
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootpassword6793
          image: mysql:8.0
          name: mysql
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-data
            - mountPath: /docker-entrypoint-initdb.d/db.sql
              name: mysql-cm1
              subPath: db.sql
            - mountPath: /etc/mysql/conf.d/my.cnf
              name: mysql-claim2
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-data
        - configMap:
            items:
              - key: db.sql
                path: db.sql
            name: mysql-cm1
          name: mysql-cm1
        - name: mysql-claim2
          persistentVolumeClaim:
            claimName: mysql-claim2
            readOnly: true
