apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |-
    :80 {
        handle /health {
          respond "OK" 200
        }

        root * /var/www/html
        php_fastcgi php:9000
        file_server
    }

  index.php: "<?php // Placeholder for Caddy"
